AWSTemplateFormatVersion: 2010-09-09
Description: Parima - Launch Your Website using AWS in Minutes (https://github.com/formkiq/parima)

Parameters:

  HostedZone:
    Type: String
    Description: Optional. Required for custom domains - see https://console.aws.amazon.com/route53/v2/HostedZones
    Default: ''
  DomainName:
    Type: String
    Description: Optional. Required for custom domain, e.g. www.yourcompany.com
    Default: ''
  WebsiteVersion:
    Type: String
    Description: Version website to deploy
    AllowedPattern: ".+"
    Default: "v1"

Conditions:
  HasCertificate: !And [!Not [ !Equals [ !Ref HostedZone, "" ]], !Not [ !Equals [ !Ref DomainName, "" ]]]
  NoCertificate: !Or [!Equals [ !Ref HostedZone, "" ], !Equals [ !Ref DomainName, "" ]]

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      Tags:
        - Key: "Application"
          Value: "Parima"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement: 
        - 
          Action: 
            - "s3:GetObject"
          Effect: "Allow"
          Resource: 
            Fn::Join: 
              - ""
              - 
                -  !GetAtt S3Bucket.Arn
                - "/*"
          Principal:
            CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: NoCertificate
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt S3Bucket.RegionalDomainName
          Id: s3origin
          OriginPath: !Sub "/${WebsiteVersion}"
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 600
          MaxTTL: 600
          MinTTL: 0
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.1_2016
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: "Application"
          Value: "Parima"

  CloudFrontRoute53:
    Type: AWS::Route53::RecordSet
    Condition: HasCertificate
    Properties:
      Name: !Ref DomainName
      HostedZoneName: !Sub "${HostedZone}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontCertificateDistribution.DomainName

  CloudFrontCertificateDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - Certificate
    Condition: HasCertificate
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt S3Bucket.RegionalDomainName
          Id: s3origin
          OriginPath: !Sub "/${WebsiteVersion}"
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 600
          MaxTTL: 600
          MinTTL: 0
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Aliases:
        - !Ref DomainName
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
          AcmCertificateArn: !GetAtt Certificate.CertificateArn
      Tags:
        - Key: "Application"
          Value: "Parima"

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront for Parima ${S3Bucket}'

  # Create an IAM user with Access Keys to enable automated deployment of the website to this bucket
  PublishUser:
    Type: 'AWS::IAM::User'

  PublishGroup:
    Type: AWS::IAM::Group
    Properties:
      Policies:
      - PolicyName: !Sub 'publish-to-${S3Bucket}'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource:
            - !Sub 'arn:aws:s3:::${S3Bucket}'            
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListObjectsV2
            Resource:
            - !Sub 'arn:aws:s3:::${S3Bucket}'
            - !Sub 'arn:aws:s3:::${S3Bucket}/*'

  AddPublishUserToPublishGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref PublishGroup
      Users:
      - !Ref PublishUser

  PublishCredentials:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref PublishUser

  DefaultSiteResource:
    Type: Custom::DefaultSite
    Properties:
      ServiceToken: !GetAtt DefaultSiteLambda.Arn

  DefaultSiteLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListObjectsV2
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - !Sub 'arn:aws:s3:::${S3Bucket}/*'

  DefaultSiteLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Timeout: '300'
      Handler: index.handler
      Role: !GetAtt DefaultSiteLambdaRole.Arn
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          WEBSITE_VERSION: !Ref WebsiteVersion
      Code:
        ZipFile: |
          const AWS=require("aws-sdk"),https=require("https"),fs=require("fs");var s3=new AWS.S3({apiVersion:"2006-03-01"});function upload(e){const s=e.split("/").pop();return new Promise((e,o)=>{console.log("Uploading "+s+" to "+process.env.S3_BUCKET);let t=getContentTypeByFile(s),n={Bucket:process.env.S3_BUCKET,Key:process.env.WEBSITE_VERSION+"/"+s,Body:fs.createReadStream("/tmp/"+s),ContentType:t};s3.putObject(n,function(t,n){t?(console.log(t),o(t)):e(s)})})}function download(e){const s=e.split("/").pop(),o=fs.createWriteStream("/tmp/"+s);return new Promise((s,t)=>{https.get(e,e=>{200===e.statusCode?e.pipe(o):(o.close(),t(`Server responded with ${e.statusCode}: ${e.statusMessage}`))}).on("error",e=>{o.close(),t(e.message)}),o.on("finish",()=>{console.log("downloaded "+e),s("downloaded "+e)})})}function sendResponse(e,s,o,t){var n=require("https"),a=require("url");console.log("Sending response "+o);var r=JSON.stringify({Status:o,Reason:"See the details in CloudWatch Log Stream: "+s.logStreamName,PhysicalResourceId:e.StackId+"-"+e.LogicalResourceId,StackId:e.StackId,RequestId:e.RequestId,LogicalResourceId:e.LogicalResourceId,Data:t});console.log("RESPONSE BODY:\n",r);var l=a.parse(e.ResponseURL),i={hostname:l.hostname,port:443,path:l.path,method:"PUT",headers:{"content-type":"","content-length":r.length}};return console.log("SENDING RESPONSE...\n"),new Promise(function(e,s){var o=n.request(i,s=>{s.setEncoding("utf8"),console.log("statusCode:",s.statusCode),console.log("headers:",s.headers);let o="";s.on("data",e=>{o+=e}),s.on("end",()=>{console.log("response status: "+s.statusCode),console.log("response body: "+o),e([o,s.statusCode,s.headers])})}).on("error",s=>{let o=JSON.stringify(s);console.log("unable to send message"),console.log(o),e([{message:"Unable to send message"},502,null])}).on("timeout",()=>{console.log("request timeout"),e([{message:"Request has timed out"},502,null])});o.write(r),o.end()})}function getContentTypeByFile(e){var s="application/octet-stream",o=e.toLowerCase();return o.indexOf(".html")>=0?s="text/html":o.indexOf(".css")>=0?s="text/css":o.indexOf(".json")>=0?s="application/json":o.indexOf(".js")>=0?s="application/x-javascript":o.indexOf(".png")>=0?s="image/png":o.indexOf(".jpg")>=0&&(s="image/jpg"),s}module.exports.handler=(async(e,s)=>{var o=[];const t=["https://parima.s3.amazonaws.com/placeholder/index.html","https://parima.s3.amazonaws.com/placeholder/parima.png"];if(null!=e.RequestType){if("Create"===e.RequestType){for(let e of t)o.push(download(e));await Promise.all(o);var n=[];for(let e of t)n.push(upload(e));await Promise.all(n)}return"Create"===e.RequestType||"Delete"===e.RequestType||"Upload"===e.RequestType?sendResponse(e,s,"SUCCESS",{Message:"Resource "+e.RequestType+" successful!"}):sendResponse(e,s,"FAILED")}});

  Certificate:
    Type: Custom::Certificate
    Condition: HasCertificate
    Properties:
      ServiceToken: !GetAtt CertificateLambda.Arn
      DomainName: !Ref DomainName
      HostedZoneName: !Ref HostedZone
      StackName: !Ref 'AWS::StackName'

  CertificateLambdaRole:
    Type: AWS::IAM::Role
    Condition: HasCertificate
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - acm:DeleteCertificate
            - acm:RequestCertificate
            - acm:AddTagsToCertificate
            - acm:DescribeCertificate            
            - route53:ChangeResourceRecordSets
            - route53:ListHostedZonesByName
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - cloudformation:DescribeStacks
            Resource: '*'

  CertificateLambda:
    Type: AWS::Lambda::Function
    Condition: HasCertificate
    Properties:
      Runtime: nodejs12.x
      Timeout: '300'
      Handler: index.handler
      Role: !GetAtt CertificateLambdaRole.Arn
      Code:
        ZipFile: |
          const AWS=require("aws-sdk");var acm=new AWS.ACM({region:"us-east-1"}),route53=new AWS.Route53,cloudformation=new AWS.CloudFormation;const sleep=e=>new Promise(t=>setTimeout(t,e));async function findHostedZoneId(e){return new Promise((t,o)=>{var a={DNSName:e};route53.listHostedZonesByName(a,function(e,a){e?o(e):t(a.HostedZones[0].Id)})})}async function updateRoute53(e,t){let o=await findHostedZoneId(e),a=[];for(let n of t.Certificate.DomainValidationOptions)if(n.ResourceRecord&&n.ResourceRecord.Name){var i={ChangeBatch:{Changes:[{Action:"UPSERT",ResourceRecordSet:{Name:n.ResourceRecord.Name,ResourceRecords:[{Value:n.ResourceRecord.Value}],TTL:60,Type:n.ResourceRecord.Type}}]},HostedZoneId:o};a.push(route53.changeResourceRecordSets(i).promise())}else console.log("Missing DNS Record, going to sleep and will try again"),a.push(sleep(1e4).then(()=>updateRoute53(e,t)));return Promise.all(a)}async function waitForValidation(e){return acm.waitFor("certificateValidated",{CertificateArn:e}).promise()}async function findCertificateArn(e){var t={StackName:e};return new Promise((e,o)=>{cloudformation.describeStacks(t,function(t,a){if(t)o(t);else{var i="";for(let e of a.Stacks[0].Outputs)"Certificate"==e.OutputKey&&(i=e.OutputValue);e(i)}})})}async function deleteCertificate(e){return console.log("deleting certificate "+e),acm.deleteCertificate({CertificateArn:e}).promise()}async function describeCertificate(e){return acm.describeCertificate({CertificateArn:e}).promise()}async function createCertificate(e,t){var o={DomainName:t,DomainValidationOptions:[{DomainName:t,ValidationDomain:e}],SubjectAlternativeNames:["*."+t],Tags:[{Key:"Application",Value:"Parima"}],ValidationMethod:"DNS"};return acm.requestCertificate(o).promise()}async function sendResponse(e,t,o,a){var i=require("https"),n=require("url"),r=JSON.stringify({Status:o,Reason:"See the details in CloudWatch Log Stream: "+t.logStreamName,PhysicalResourceId:e.StackId+"-"+e.LogicalResourceId,StackId:e.StackId,RequestId:e.RequestId,LogicalResourceId:e.LogicalResourceId,Data:a}),s=n.parse(e.ResponseURL),c={hostname:s.hostname,port:443,path:s.path,method:"PUT",headers:{"content-type":"","content-length":r.length}};return new Promise(function(e,t){var o=i.request(c,t=>{t.setEncoding("utf8");let o="";t.on("data",e=>{o+=e}),t.on("end",()=>{e([o,t.statusCode,t.headers])})}).on("error",t=>{JSON.stringify(t);e([{message:"Unable to send message"},502,null])}).on("timeout",()=>{e([{message:"Request has timed out"},502,null])});o.write(r),o.end()})}module.exports.handler=(async(e,t)=>{if(console.log(JSON.stringify(e)),null!=e.RequestType){if("Create"===e.RequestType){let o=e.ResourceProperties.DomainName,a=e.ResourceProperties.HostedZoneName;return createCertificate(a,o).then(e=>(console.log("created certificate "+e.CertificateArn),describeCertificate(e.CertificateArn))).then(e=>(console.log("adding certificate verification DNS entries"),updateRoute53(a,e),e.Certificate)).then(e=>(console.log("waiting DNS to be updated so certificate can be validated"),waitForValidation(e.CertificateArn))).then(o=>sendResponse(e,t,"SUCCESS",{CertificateArn:o.Certificate.CertificateArn})).catch(o=>(console.log("error "+o),sendResponse(e,t,"FAILED")))}if("Delete"===e.RequestType){return findCertificateArn(e.ResourceProperties.StackName).then(e=>deleteCertificate(e)).then(o=>sendResponse(e,t,"SUCCESS",{})).catch(o=>sendResponse(e,t,"SUCCESS"))}return"Update"===e.RequestType?sendResponse(e,t,"SUCCESS",{}):sendResponse(e,t,"FAILED")}});

Outputs:
  Certificate:
    Condition: HasCertificate
    Description: 'Certificate'
    Value: !GetAtt Certificate.CertificateArn
  AccessKeyId:
    Description: 'S3 Access Key'
    Value: !Ref PublishCredentials
  AccessKeySecret:
    Description: 'S3 Secret Key'
    Value: !GetAtt PublishCredentials.SecretAccessKey
  WebsiteUrl:
    Description: 'Website Url'
    Value: !If [HasCertificate, !Sub "https://${DomainName}", !Sub "https://${CloudFrontDistribution.DomainName}"]
  S3Bucket:
    Description: 'S3 Bucket'
    Value: !Ref S3Bucket
  SyncCommand:
    Description: 'Sync Current Directory to S3'
    Value: !Sub "aws s3 sync . s3://${S3Bucket}/${WebsiteVersion}"    